plugins {
    id "com.android.application"
}

android {
    namespace "com.dongxiao.practice"
    compileSdk 35

    defaultConfig {
        applicationId "com.dongxiao.practice"
        minSdk 23
        targetSdk 35
        versionCode 21
        versionName "0.4.12"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
